### ISSUE TITLE
makeAggregateBom appends BOMs twice

### ISSUE THREAD

**Issue by pho3nixx** [CycloneDX/cyclonedx-maven-plugin#106]
Steps to reproduce:
- create a new simple Maven project, e.g. via https://start.spring.io/
- run `mvn clean org.cyclonedx:cyclonedx-maven-plugin:2.4.1:makeAggregateBom install`

You will see, that `target/bom.xml` and `target/bom.json` are appended and installed twice to the build. This causes problems when `deploy`ing to a release repository later on, that doesn't allow overwriting of artifacts.

This happens since Version 2.4.1 and was probably introduced in https://github.com/CycloneDX/cyclonedx-maven-plugin/commit/448f71677e7b2b5f243f9ba882233f3e4a669105
Removing [this line](https://github.com/CycloneDX/cyclonedx-maven-plugin/commit/448f71677e7b2b5f243f9ba882233f3e4a669105#diff-bd3dbf9d6a94bb33c0da3fb6e02431ebe77876101c6a97a44c161565571d8fbcR146) from the mentioned commit solves the problem for me locally, but I'm unsure of side-effects.

**Comment by stevespringett** [comment]
Thanks for the reporting. Commit https://github.com/CycloneDX/cyclonedx-maven-plugin/commit/97bb8995d4699e8964cc5e918884dfe5b2a5457e should fix the issue in a way that doesn't impact the dependency graph. 

Issue will be resolved in v2.5.0

Please reopen if the issue persists.
