### ISSUE TITLE
[ERROR] An error occurred attempting to read POM

### ISSUE THREAD

**Issue by zg2pro** [CycloneDX/cyclonedx-maven-plugin#117]
Hi,

I'm meeting fatal erros during makeAggregateBom when I embed this dependency: 
`<dependency>
          <groupId>org.activiti</groupId>
            <artifactId>activiti-engine</artifactId>
            <version>5.14</version>
        </dependency>`

Also in the error stack:

> 17:05:27  [ERROR] An error occurred attempting to read POM
> 17:05:27  org.codehaus.plexus.util.xml.pull.XmlPullParserException: only whitespace content allowed before start tag and not \ufffd (position: START_DOCUMENT seen \ufffd... @1:1) 
> 17:05:27      at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog (MXParser.java:1862)
> 17:05:27      at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl (MXParser.java:1698)

Unfortunately I won't be able to take the latest version of activiti-engine in my application. Can you do something with the plugin?

**Comment by zg2pro** [comment]
Hi @stevespringett 

That's odd, I have errors even on a small dedicated project with just this dependency. And I have it both on Windows and Linux. What JDK are you using ? I'm on an oracle jdk 11.

BR
Gregory

**Comment by stevespringett** [comment]
Here's the output from `mvn --version`:
```
steve@Prometheus issue-117 % mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

Here's the [pom.xml.zip](https://github.com/CycloneDX/cyclonedx-maven-plugin/files/6969923/pom.xml.zip) I used and simply executed `mvn package`.

**Comment by zg2pro** [comment]
Hi @stevespringett 

It seems it is OS-related: I created a small github repo with your pom.xml and added a travis.yml file for CI. You can see the results in here: https://travis-ci.com/github/zg2pro/cyclonedx-plugin-issue-117
If you look at the linux logs (4.1), it will be clean, BUT if you look at the windows vm logs (4.2), you'll see the error.

Best regards
Gregory

**Comment by stevespringett** [comment]
The pom for activiti-root-5.14 has a Byte Order Marker whereas the other poms from the activiti project do not. One of the dependencies seems to be failing when parsing this, which is really odd. The CycloneDX Maven plugin doesn't perform any XML parsing, so I'm at a bit of a loss for how to fix it. Also, reproducing the issue and debugging it will be an issue as I do not have access to a Windows development machine.

<img width="700" alt="Screen Shot 2021-08-16 at 10 27 44 PM" src="https://user-images.githubusercontent.com/3878933/129659283-d75901cd-e1f5-4064-a0db-2f32ff2b99c4.png">

**Comment by zg2pro** [comment]
Hi @stevespringett 
I created a pull request for you: https://github.com/CycloneDX/cyclonedx-maven-plugin/pull/121
BR 
Gregory

**Comment by stevespringett** [comment]
v2.5.2. has been published to Maven Central. Thanks again for the PR
