### ISSUE TITLE
Unsupported major.minor version 52.0 while running cyclonedx-maven-plugin:makeAggregateBom 1.3.1

### ISSUE THREAD

**Issue by ilsire** [CycloneDX/cyclonedx-maven-plugin#14]
Hi, 
I'm running mvn cyclonedx-maven-plugin:makeAggregateBom 1.3.1 under maven 3.5.4 / java jdk1.8.0_73 on linux CentOS 6.x in automation with Jenkins

I'm facing with this exception **Unsupported major.minor version 52.0** due to an **API incompatibility** building a multi job:

`...

11:19:02 [DEBUG] Configuring mojo org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeBom from plugin realm ClassRealm[plugin>org.cyclonedx:cyclonedx-maven-plugin:1.3.1, parent: sun.misc.Launcher$AppClassLoader@72b81eaa]
11:19:02 [WARNING] Error injecting: org.cyclonedx.maven.CycloneDxMojo
11:19:02 java.lang.TypeNotPresentException: Type org.cyclonedx.maven.CycloneDxMojo not present
11:19:02     at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:147)
11:19:02     at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
11:19:02     at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
11:19:02     at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)

...

11:19:02 Caused by: java.lang.UnsupportedClassVersionError: org/cyclonedx/maven/CycloneDxMojo : Unsupported major.minor version 52.0

...

`11:19:02 [ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeBom (default-cli) on project XXXXX: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeBom failed: Unable to load the mojo 'makeBom' in the plugin 'org.cyclonedx:cyclonedx-maven-plugin:1.3.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/cyclonedx/maven/CycloneDxMojo : Unsupported major.minor version 52.0
11:19:02 [ERROR] -----------------------------------------------------
11:19:02 [ERROR] realm =    plugin>org.cyclonedx:cyclonedx-maven-plugin:1.3.1
11:19:02 [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
11:19:02 [ERROR] urls[0] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/cyclonedx/cyclonedx-maven-plugin/1.3.1/cyclonedx-maven-plugin-1.3.1.jar
11:19:02 [ERROR] urls[1] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/cyclonedx/cyclonedx-core-java/1.1.2/cyclonedx-core-java-1.1.2.jar
11:19:02 [ERROR] urls[2] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
11:19:02 [ERROR] urls[3] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/commons-io/commons-io/2.6/commons-io-2.6.jar
11:19:02 [ERROR] urls[4] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/com/github/package-url/packageurl-java/1.0.0/packageurl-java-1.0.0.jar
11:19:02 [ERROR] urls[5] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
11:19:02 [ERROR] urls[6] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar
11:19:02 [ERROR] urls[7] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/xerces/xercesImpl/2.12.0/xercesImpl-2.12.0.jar
11:19:02 [ERROR] urls[8] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
11:19:02 [ERROR] urls[9] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
11:19:02 [ERROR] urls[10] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
11:19:02 [ERROR] urls[11] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
11:19:02 [ERROR] urls[12] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
11:19:02 [ERROR] urls[13] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
11:19:02 [ERROR] urls[14] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar
11:19:02 [ERROR] urls[15] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
11:19:02 [ERROR] urls[16] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
11:19:02 [ERROR] urls[17] = file:/appserv/jenkins/workspace/aaaa/aaaa_XXX_cyclondx_test/.repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
11:19:02 [ERROR] Number of foreign imports: 1
11:19:02 [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
11:19:02 [ERROR] 
11:19:02 [ERROR] -----------------------------------------------------
11:19:02 [ERROR] 
11:19:02 [ERROR] -> [Help 1]
11:19:02 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeBom (default-cli) on project XXX: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeBom failed: Unable to load the mojo 'makeBom' in the plugin 'org.cyclonedx:cyclonedx-maven-plugin:1.3.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/cyclonedx/maven/CycloneDxMojo : Unsupported major.minor version 52.0`

The error comes when you are trying to run a class compiled using Java 1.8 compiler into a lower JDK version, so we tried different versions of maven 3.0.5, 3.1.1, 3.2.5 and 3.5.4 but the above error persists.

Could you please help me?
Thank you

**Comment by stevespringett** [comment]
This is a Java warning and has nothing to do with CycloneDX. Multi-module Maven projects can use different versions of Java in the same build. Ensure that Maven is being executed with Java 8 or higher and that the parent pom and each module does not override the jdk version with a lower version.

**Comment by ilsire** [comment]
Hi, you are right analyzing the mvn I identified a old JAVA_HOME that forced jdk 1.7
```
Apache Maven 3.5.4 (xxxxxxx 2018-06-17T20:33:14+02:00)
Maven home: /jenkins/tools/maven-3.5.4
Java version: 1.7.0_45, vendor: Oracle Corporation, runtime: /opt/jdk1.7.0_45_x64/jre

```
Once removed it worked
Thank you
