### ISSUE TITLE
Not able to identify any issues in Dashboard

### ISSUE THREAD

**Issue by rfeiten** [CycloneDX/cyclonedx-maven-plugin#142]
Hello! I installed DependencyTrack using the recommended method over Docker Swarm, using a Microsoft SQL Server database as opted DB. 

I have created a couple projects and upload the SBOM through the API, although, for some reason, I can't see the vulnerabilities updated in the general dashboard. It shows "0" for everything. 

![image](https://user-images.githubusercontent.com/42576933/143469298-eab6ce0a-3f06-464f-8c1e-af9d3b1f1a22.png)

But, if we look at the project itself, it has some vulnerabilities. 
![image](https://user-images.githubusercontent.com/42576933/143469487-010fb5ce-53c2-483e-ae43-52461186522e.png)

I tried to upload manually by hitting the refresh button, which sends a signal to the API as per the logs

`15:32:50.507 INFO [EventService] An singleton event (MetricsUpdateEvent) was received but another singleton event of the same type is already in progress. Skipping.`

Although, it never completes or it stays always everything as zero. From the UI itself, tried to open console to see possible errors, but just see this one 

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'render')
    at Dashboard.vue:224`

Is it something it might be misconfigured from my side? 

Thanks in advance.

**Comment by stevespringett** [comment]
Metrics are refreshed asynchronously. They are not immediate.
