### ISSUE TITLE
Usage section

### ISSUE THREAD

**Issue by andreagalle** [CycloneDX/cyclonedx-maven-plugin#145]
Please, provide for a usage section in the README.md file.

Is `mvn cyclonedx:makeBom` enough?

**Comment by stevespringett** [comment]
Usage is in the readme and specifically recommends adding a section to the pom.

Executing CycloneDX from the command line with `mvn`... will yield results. However Maven has a lifecycle and that lifecycle is important for accuracy of component inventory and dependency relationships. Depending on the project, you may get unexpected results running from the command line.

**Comment by hboutemy** [comment]
@andreagalle some work done in #243 : do you see anything else to add?
