### ISSUE TITLE
License information in SBOM

### ISSUE THREAD

**Issue by andresghelarducci** [CycloneDX/cyclonedx-maven-plugin#151]
Hi, 
I am using v.2.5.3 of the plugin in a web application , the generated JSON file sometimes the license property is an empty array(see en extract below where I removed hashes content): this occurs only for a small percentage of the libraries used by the application.
If I look in the maven repository sites I easily find that license is defined for the library (i.e https://mvnrepository.com/artifact/org.antlr/antlr-runtime/3.3)
Full BOM is attached.

Can you explain the reason for this behavior?
Is there something I can do to get the license in the BOM file
```json
{
      "group" : "org.antlr",
      "name" : "antlr-runtime",
      "version" : "3.3",
      "description" : "A framework for constructing recognizers, compilers, and translators from grammatical descriptions containing Java, C#, C++, or Python actions.",
      "hashes" : [      ],
      "licenses" : [ ],
      "purl" : "pkg:maven/org.antlr/antlr-runtime@3.3?type=jar",
      "externalReferences" : [
        {
          "type" : "vcs",
          "url" : "http://fisheye2.cenqua.com/browse/antlr"
        }
      ],
      "type" : "library",
      "bom-ref" : "pkg:maven/org.antlr/antlr-runtime@3.3?type=jar"
    }
```
[bom.txt](https://github.com/CycloneDX/cyclonedx-maven-plugin/files/8003399/bom.txt)

Thanks
Andres

**Comment by stevespringett** [comment]
In this example, antlr-runtime does not have a license defined in the pom.xml
https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.3/antlr-runtime-3.3.pom

The antlr-runtime pom has antlr-master defined as its parent and antlr-master also does not have a license defined.
https://repo1.maven.org/maven2/org/antlr/antlr-master/3.3/antlr-master-3.3.pom

My guess would be that mvnrepository.com is picking up the BSD license by looking into a submodule of antlr-master, the antlr3-maven-plugin module, and seeing a BSD license there. This approach may produce erroneous data as its possible to have a different license for every submodule, in which case mvnrepository would be wrong.

The fix would be to have the antlr project properly define its license, which in newer versions of the project, they have.
https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.9.3/antlr4-master-4.9.3.pom

**Comment by andresghelarducci** [comment]
Hi Steve,
thanks for the answer , so practically missing information in a library are due to lack of data inside the associated pom file?

Andres

**Comment by stevespringett** [comment]
>  so practically missing information in a library are due to lack of data inside the associated pom file?

Correct.
