### ISSUE TITLE
Complete bom file for maven project

### ISSUE THREAD

**Issue by stboiss** [CycloneDX/cyclonedx-maven-plugin#2]
is it expected that the plugin can produce a complete BOM file for a maven project ?

**Comment by stevespringett** [comment]
When compete, yes, that's the goal.

**Comment by stevespringett** [comment]
I don't have a time frame for it. I'd like to get it done this year but I know I wont have any time in the next few months to work on it.

**Comment by stevespringett** [comment]
Yes, the expectation is that a bom.xml will be the result of running the plugin with all components listed in the bom being directly under the <components> node (without hierarchy).

**Comment by stevespringett** [comment]
v1.0.0 of the plugin was released to Maven Central moments ago. It usually takes a few hours for central to sync. The GAV and an example is listed in the project readme.
