### ISSUE TITLE
ClassNotFoundException: org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by reallyinsane** [CycloneDX/cyclonedx-maven-plugin#20]
Same like #8. Just trying to creating a bom from a project. 

cyclonedx-maven-plugin: 1.4.1/1.4.0
Maven: 3.5.0
Java: 1.8.0_192

Also adding xml-apis to dependencies of plugin as suggested in #8 doesnt help.

Any suggestions?

**Comment by stevespringett** [comment]
If there's a project on GitHub that I can use to reproduce the issue with, let me know. Otherwise, I have no idea.
