### ISSUE TITLE
Goal descriptions missing

### ISSUE THREAD

**Issue by bmarwell** [CycloneDX/cyclonedx-maven-plugin#206]
The site does not include the "goals" descriptions:

https://cyclonedx.github.io/cyclonedx-maven-plugin/

Here's an example where goals have descriptions: https://maven.apache.org/plugins/maven-war-plugin/plugin-info.html

**Comment by hboutemy** [comment]
see also #237

**Comment by hboutemy** [comment]
and #13 : clearly defining what is expected from each goals does not seems obvious
