### ISSUE TITLE
Configuration has no javadoc

### ISSUE THREAD

**Issue by bmarwell** [CycloneDX/cyclonedx-maven-plugin#208]
I added this to my pom.xml:

```
  <configuration>
            <projectType>library</projectType>
            <schemaVersion>1.4</schemaVersion>
            <includeBomSerialNumber>true</includeBomSerialNumber>
            <includeCompileScope>true</includeCompileScope>
            <includeProvidedScope>true</includeProvidedScope>
            <includeRuntimeScope>true</includeRuntimeScope>
            <includeSystemScope>true</includeSystemScope>
            <includeTestScope>false</includeTestScope>
            <includeLicenseText>false</includeLicenseText>
            <outputReactorProjects>true</outputReactorProjects>
            <outputFormat>all</outputFormat>
            <outputName>bom</outputName>
        </configuration>
```

I hovered over each value, but it does not contain or onlyvery little javadoc.
For example, projectType should list all possible valid project types AND WHEN TO USE WHICH.
The warning on the console is somewhat helpful as it lists valid values, but still does not mention when to use which.

This is slightly related to #206, but #206 is about the goal descriptions which will generate the "Goals" site. Without this issue, there would be no description  of parameters.

**Comment by breun** [comment]
I'm also wondering what some of these configuration options do. Is `projectType` a free-form field, or is there a predefined list of types? What is the effect of overriding `projectType` exactly?

What does `outputReactorProjects` do?

I think the valid values for `outputFormat` are `all`, `xml` and `json`?

**Comment by stevespringett** [comment]
@breun `projectType` must match one of the enums for the version of the CycloneDX spec being used. For v1.4 of the spec, see https://cyclonedx.org/docs/1.4/json/#components_items_type

Maven reactors are described in the Maven documentation. See https://maven.apache.org/guides/mini/guide-multiple-modules.html. Therefore `outputReactorProjects` will output a BOM for every module in a multi-module Maven project.

**Comment by hboutemy** [comment]
documentation added in #230
