### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by ben-gineer** [CycloneDX/cyclonedx-maven-plugin#21]
We've enabled the CycloneDX maven plugin on our multi-module projects, and it's adding quite a performance hit to our builds.

Our config is:

            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>1.4.1</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>makeAggregateBom</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <schemaVersion>1.1</schemaVersion>
                    <includeBomSerialNumber>true</includeBomSerialNumber>
                    <includeCompileScope>true</includeCompileScope>
                    <includeProvidedScope>true</includeProvidedScope>
                    <includeRuntimeScope>true</includeRuntimeScope>
                    <includeSystemScope>true</includeSystemScope>
                    <includeTestScope>false</includeTestScope>
                </configuration>
            </plugin>

This results in CycloneDX generating boms for every module:
`
07:01:19  [INFO] --- cyclonedx-maven-plugin:1.4.1:makeAggregateBom (default) @ my-module ---
07:02:55  [INFO] CycloneDX: Creating BOM
07:02:55  [INFO] CycloneDX: Writing BOM
07:02:55  [INFO] CycloneDX: Validating BOM
`

i.e. it adds 90 seconds to every module in our build. We have dozens of modules.

How can we improve the performance of this?

Do we need to run it on every child module in a multi-module build? Or should we configure it just on the root maven module?

Thanks

**Comment by ben-gineer** [comment]
Just spotted https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/13

I will try the suggestion

**Comment by stevespringett** [comment]
Closing
