### ISSUE TITLE
Could not generate SBOM - dependency is missing

### ISSUE THREAD

**Issue by jojen** [CycloneDX/cyclonedx-maven-plugin#210]
my ~/.m2/settings.xml file contains the login information for this repo

makeBom aborts with this info:

Could not find artifact org.apache.logging.log4j:log4j-api-java9:pom:2.10.0 in mycompany-nexus-maven-releases (https://nexus.mycompany.com/repository/maven-releases/)

**Comment by stevespringett** [comment]
Thanks for reporting. I do not have a way to reproduce, so any additional information would be appreciated.

**Comment by 2013kaa** [comment]
I have the same problem. 
The settings.xml of the project specifies the local nexus repository where artifacts are uploaded, including the example.jar file. When running a cyclonedx job, an error occurs:
[ERROR] Failed to execute goal on project example: Could not resolve dependencies for project example:jar:1.0.0: Could not find artifact example:jar:1.11 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

how can i solve my problem? what data do you need to help me?

**Comment by jojen** [comment]
@2013kaa in my case i use spring boot. i cannot find this dependency in my dependency tree.

if i change the spring boot version this error does not show up any more.

**Comment by sanderv** [comment]
I can reproduce this error without specifying a repo in settings.xml:
`Could not find artifact org.apache.logging.log4j:log4j-api-java9:pom:2.13.3 in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)`

Cloning the git repo for the cyclone plugin and updating the `maven-dependency-tree` dependency to the latest version (3.2.0) solved this for me.
```
        <dependency>
            <groupId>org.apache.maven.shared</groupId>
            <artifactId>maven-dependency-tree</artifactId>
            <version>3.2.0</version>
        </dependency>
```

**Comment by sanderv** [comment]
PR https://github.com/CycloneDX/cyclonedx-maven-plugin/pull/213

**Comment by stevespringett** [comment]
Thanks for identifying the root cause and subsequent PR @sanderv. Much appreciated. In the process of pushing v2.7.2 of the plugin to Central. Should be available shortly.
