### ISSUE TITLE
java.lang.StackOverflowError while invoking cyclonedx-maven-plugin:2.1.0:makeAggregateBom

### ISSUE THREAD

**Issue by marioja** [CycloneDX/cyclonedx-maven-plugin#214]
In our CI build server we are seeing a few occurrences of this error.  We have been able to reproduce it on the command line and when the plugin is invoked on a branch new empty maven local repository the error disappear.  This error has occured using version 2.1.0, 2.20, 2.3.0, 2.4.1 and 2.5.3.  The stack trace is a little different but the same error occurs.
```
Exception in thread "main" java.lang.StackOverflowError
	at java.io.InputStream.<init>(InputStream.java:45)
	at java.io.FileInputStream.<init>(FileInputStream.java:123)
	at org.cyclonedx.maven.BaseCycloneDxMojo.readPom(BaseCycloneDxMojo.java:680)
	at org.cyclonedx.maven.BaseCycloneDxMojo.retrieveParentProject(BaseCycloneDxMojo.java:629)
	at org.cyclonedx.maven.BaseCycloneDxMojo.getClosestMetadata(BaseCycloneDxMojo.java:463)
	at org.cyclonedx.maven.BaseCycloneDxMojo.getClosestMetadata(BaseCycloneDxMojo.java:465)
(1,017 more occurences)
```

**Comment by stevespringett** [comment]
Thanks for reporting. The current version of the Maven plugin is 2.7.2. Do your still see the stack trace with this version? If so, do you have a pom that can reproduce the issue?

**Comment by marioja** [comment]
I cannot reproduce it with 2.7.2 because I am using -DshcemaVersion=1.1 in my live production usecase.  I am working on a reproducible test case but it is difficult since this is using proprietary POM and builds.  I modified 2.1.0 to print artifact and maven project when calling getClosestMetadata() and will post a sanitized version soon.

**Comment by marioja** [comment]
The problem occurs on our CI build server on Windows when the following multi-module maven project is installed in the local maven repository:

```
com.company.app1:app1web:1-SNAPSHOT:pom
  com.company.app1:App1Web:1-SNAPSHOT:war
  com.company.app1:App1Web:1-SNAPSHOT:pom
  com.company.app1:common:1-SNAPSHOT:jar
  com.company.app1:common:1-SNAPSHOT:pom
```
In our case since during maven install the POM for the WAR is installed second, the POM for the App1Web WAR will override the parent POM since they get written to the same folder due to Windows not supporting case sensitive folder names.  Subsequently when cyclonedx maven plugin makeAggregateBom is invoked it requests the parent for common but this will return the WAR POM file (since this is the last one written).  When it looks for the parent it will retrieve the WAR POM file again and so on in an infinite loop.

The problem is not really in cyclonedx although it might be advantageously to detect and report such a dependency loop.

This project configuration occurs frequently in our environment.

**Comment by marioja** [comment]
If you do not plan to detect and reports loops than as far as I am concerned this issue can be closed.
