### ISSUE TITLE
Exclude or set metadata/timestamp for Reproducible Builds

### ISSUE THREAD

**Issue by olfuerniss** [CycloneDX/cyclonedx-maven-plugin#226]
At the moment (v2.7.3) the ```metadata/timestamp``` gets set - in the generated JSON - to the current date. For Reproducible Builds it is necessary that this does not get changed on every build. 

It would be nice if a configuration option could be added to exclude the ```metadata/timestamp``` like it is possible for the ```serialNumber``` with ```includeBomSerialNumber```. 

Or let us set a date like provided by ```${git.commit.time}``` from the [git-commit-id-maven-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin). Example of such a date: ```2022-11-24T13:21:08+0100```

**Comment by stevespringett** [comment]
The consensus among NTIA SBOM working group participants is that SBOMs should not conform to reproducible builds. Per [NTIA minimum elements](https://www.ntia.gov/files/ntia/publications/sbom_minimum_elements_report.pdf), a timestamp is required and is defined as: "Record of the date and time of the SBOM data assembly". This is the timestamp of when the SBOM was created. There were other data fields which did not make the minimum elements list which also could not realistically be reproduced.

With that said, I'd welcome a PR that omitted the timestamp.

**Comment by olfuerniss** [comment]
Steve, to omit the metadata timestamp. Which version do you prefer?

1. Additional config option `includeBomMetadataTimestamp` = `true`|`false`

2. If the Maven project property `project.build.outputTimestamp` is set, the metadata timestamp gets omitted. Described in the [reproducible builds](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) documentation: Set the property `project.build.outputTimestamp` to "Enable Reproducible Builds mode for plugins, ...". 

Or as a combination: (1.) or (2.) ?


P.S. The bnd-maven-plugin uses the Maven project property since 2020: [Issue](https://github.com/bndtools/bnd/issues/3521#issuecomment-687905241)

**Comment by hboutemy** [comment]
FYI, PMD has a large history of reproducible builds https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/README.md

in latest 7.0.0 release candidates, it added CycloneDX SBOMs in their release binary archive, which now makes the release binary non-reproducible any more

**Comment by hboutemy** [comment]
@olfuerniss what do you think about #353 ?
