### ISSUE TITLE
Maven properties are not inherited properly

### ISSUE THREAD

**Issue by alerosmile** [CycloneDX/cyclonedx-maven-plugin#233]
Many project methods (e.g. `Maven.getIssueManagement()`) required the Maven properties to be properly resolved. If such an entry in the pom contains Maven properties, the CycloneDX plugin fails to write the data to the bom because it does not resolve the properties. The pom file is read manually and although the `BaseCycloneDxMojo.getClosestMetadata()` method walks up the Maven hierarchy, it does not resolve the Maven properties.

The Maven `ModelBuilder` could be used instead to read the pom and let Maven do the rest. There seems to be a pretty easy solution for this: https://stackoverflow.com/a/39609354

**Comment by stevespringett** [comment]
Thanks for the info and the hint. If this works, this could potentially eliminate a lot of code from BaseCycloneDxMojo, which would be ideal. Do you have a sample project that can reproduce this issue? 

I've incorporated the changes into my local dev environment and will be testing with dropwizard, keycloak, and webgoat, all of which are multi-module projects.

**Comment by alerosmile** [comment]
@stevespringett - I've created a simple test project where some properties are inherited in different ways.  You can try to build the `artifact` project with the `config.site-snapshots` profile activated or not - it works as expected now.

It probably would be better to use the model from the project to be built directly (`getProject().getModel()`) instead of generating it again using `getEffectiveMavenProject()`. Use `getEffectiveMavenProject()` only for the dependencies where the model is not already provided.

[depTest.zip](https://github.com/CycloneDX/cyclonedx-maven-plugin/files/10345859/depTest.zip)
