### ISSUE TITLE
command line properties does not take precedence over pom defined one

### ISSUE THREAD

**Issue by valdar** [CycloneDX/cyclonedx-maven-plugin#248]
If you have a plugin config property defined in the pom like:
```xml
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                ...
                <configuration>
                    ...
                    <outputName>configuredName</outputName>
                </configuration>
            </plugin>
```
and run the plugin passing a corresponding command line property like:
```bash
mvn clean -DoutputName=overrideName org.cyclonedx:cyclonedx-maven-plugin:2.7.3:makeAggregateBom
```
the command line passed property is ignored. I would expect it to take precedence over the one in the pom like it is in some (most?) parts of maven.

**Comment by valdar** [comment]
I have also created a PR with a test that better describe and reproduce the issue: https://github.com/CycloneDX/cyclonedx-maven-plugin/pull/250

**Comment by hboutemy** [comment]
AFAIK, this is Maven behaviour (I need time to find a reference): CycloneDX Maven plugin cannot do anything

**Comment by robertk3s** [comment]
If that helps, you can set _properties_ in Maven via system property. For example see here https://www.baeldung.com/maven-arguments.

**Comment by hboutemy** [comment]
closing issue as thiscan't be changed in cyclonedx-maven-plugin, and advice on workaround provided

**Comment by hboutemy** [comment]
notice that given the goal parameter uses `outputName` property as default value, you'll get your expected result if you don't define a fixed value in the plugin configuration, but you define a property value in `pom.xml`

```
    <properties>
        <outputName> configuredName</outputName>
    </properties>
```

such property in `pom.xml` still can be overridden on CLI: `mvn -DoutputName=overrideName package`

in #280 , I'm providing an example with `cyclonedx.verbose` to turn off verbosity by default, but let user active with CLI `-Dcyclonedx.verbose`
