### ISSUE TITLE
Allow specifying the full output path

### ISSUE THREAD

**Issue by ctron** [CycloneDX/cyclonedx-maven-plugin#271]
When creating an SBOM, one can currently only influence a part of the name.

However, assuming you want to further work with the file in an automated process, it might be good to have the ability to directly specify the output file, without the need to synchronize calls and copy around files later on.

Currently it is constructed as:

https://github.com/CycloneDX/cyclonedx-maven-plugin/blob/edb81bfba5b761e44751cddd837dc620a136dcee/src/main/java/org/cyclonedx/maven/BaseCycloneDxMojo.java#L649

It would be great of this could be overridden by a property, like `-Dcyclonedx.outputFile=/some/where/else/my.bom`.

**Comment by hboutemy** [comment]
well probably need to revive #150 ...

**Comment by hboutemy** [comment]
@ctron I finally reworked everything because code had changed much: please check #279
