### ISSUE TITLE
Manually packaged plugins cannot be used

### ISSUE THREAD

**Issue by LIFEcmd** [CycloneDX/cyclonedx-maven-plugin#287]
Manually packaged plugins cannot be used
mvn clean install   （Successfully packaged as a jar package）
![image](https://user-images.githubusercontent.com/66239815/220417948-3acc7290-7f79-43cd-88d7-273a3896a40a.png)

Introducing the plugin in a new project runs
![image](https://user-images.githubusercontent.com/66239815/220418044-9c5a55df-fdd2-48dc-a7be-56907fd8af8a.png)

An exception occurred, is there any solution?
![image](https://user-images.githubusercontent.com/66239815/220417391-9b754af3-ef61-4e49-9ec2-62cad7fcf2ac.png)

**Comment by hboutemy** [comment]
use an official release like 2.7.5?

**Comment by hboutemy** [comment]
no answer, closing
