### ISSUE TITLE
License Merge

### ISSUE THREAD

**Issue by oers** [CycloneDX/cyclonedx-maven-plugin#290]
It would be really Helpful to have a license merge feature like the license plugin

https://www.mojohaus.org/license-maven-plugin/add-third-party-mojo.html#licenseMerges

To allow something like this:
                              <licenseMerges>
                                        <licenseMerge>The Apache Software License, Version 2.0|Apache License, Version
                                            2.0|Apache Public License 2.0|Apache 2.0|Apache 2.0 License|Apache License
                                            Version 2.0|Apache 2|Apache-2.0|The Apache License, Version 2.0|Apache
                                            License 2.0
                                        </licenseMerge>
                                    </licenseMerges>
                                    
Licenses are badly named in the java ecosystem. so this would help to have it normalized in the bom.-

**Comment by stevespringett** [comment]
The Maven plugin relies on CycloneDX Core Java which intern uses a license mapping file. See https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/resources/license-mapping.json
