### ISSUE TITLE
HTTP Proxy Support when running behind a corporate proxy

### ISSUE THREAD

**Issue by RaphC** [CycloneDX/cyclonedx-maven-plugin#32]
Hi,

Is it possible to support a property which allow spdx-tools to use a corporate proxy when  invoking https://spdx.org/licenses/licences.json and https://spdx.org/licenses/<licence name>.json ?

Regards

**Comment by RaphC** [comment]
My current workaround is to set -Dhttps.proxyHost in MAVEN_OPTS

**Comment by stevespringett** [comment]
The project accept pull requests ;-)

**Comment by RaphC** [comment]
ok. I will try to work on this issue.

**Comment by stevespringett** [comment]
Closing. v2.0.0 will no longer use SPDX tools.
