### ISSUE TITLE
我在使用“ mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -Dfile.encoding=UTF-8”命令是报错如下

### ISSUE THREAD

**Issue by wzd-hash** [CycloneDX/cyclonedx-maven-plugin#329]
> 
![image](https://user-images.githubusercontent.com/59039445/230569570-2e2ebdd3-17f3-4c54-a4a4-ccee60d1064d.png)

**Comment by hboutemy** [comment]
2.7.4 is now obsolete and was known to not deal well with encoding: please try with 2.7.6

**Comment by wzd-hash** [comment]
> 
![image](https://user-images.githubusercontent.com/59039445/230808513-febe80d9-d11a-4d07-a4c1-cea0edcf93aa.png)

**Comment by wzd-hash** [comment]
![image](https://user-images.githubusercontent.com/59039445/230808581-e467a106-77db-4e4f-b001-79cea1d284aa.png)

**Comment by wzd-hash** [comment]
Version 2.7.6 still exists

**Comment by hboutemy** [comment]
oh, I did not expect the same issue with 2.7.6: can you provide us a reproducer project so we can investigate, please?

**Comment by hboutemy** [comment]
ok, in #332
