### ISSUE TITLE
I reported an error when I started the project's pom.xml after 2.7.8 version was introduced. How can I solve this problem

### ISSUE THREAD

**Issue by wzd-hash** [CycloneDX/cyclonedx-maven-plugin#352]
![image](https://user-images.githubusercontent.com/59039445/235111612-41d66e80-6220-42d2-9acc-4ad53f47b6a0.png)

**Comment by hboutemy** [comment]
you declare a **dependency** on this Maven plugin: what are you trying to achieve?

it's usually used as a plugin: https://github.com/CycloneDX/cyclonedx-maven-plugin#maven-usage

**Comment by wzd-hash** [comment]
> you declare a **dependency** on this Maven plugin: what are you trying to achieve?
> 
> it's usually used as a plugin: https://github.com/CycloneDX/cyclonedx-maven-plugin#maven-usage

Sorry, I figured it out. Using the command will automatically download the latest dependencies, I don't need to introduce them in the project
