### ISSUE TITLE
Only consider active Maven profiles when listing dependencies

### ISSUE THREAD

**Issue by MartinRied** [CycloneDX/cyclonedx-maven-plugin#364]
We have an application that is built for different target databases to include the respective JDBC drivers.
These separate builds are realized through separate maven profiles.

**Current Behaviour:**
Unfortunately when creating a SBOM, the CycloneDX maven plugins always includes the dependencies from *all* profiles
That means that even if we have the "h2" profile disabled, the H2 JDBC driver will still be listed in the SBOM.

**Desired Behaviour**
We would like to see only the active profile(s) to be taken into account when determining the dependencies that should be listed in the SBOM.

**Comment by hboutemy** [comment]
can you provide a sample project to reproduce, please?

**Comment by MartinRied** [comment]
My apologies, this is a non-issue.
While writing a minimum example POM I figured out that CycloneDX (or probably Maven itself) *does* indeed only consider dependencies from the active profiles, just as we expected.

In our case we had an additional dependency that was pulling in H2 - and which I had unfortunately missed while checking for exactly this case.
