### ISSUE TITLE
Maven documentation site incomplete

### ISSUE THREAD

**Issue by malice00** [CycloneDX/cyclonedx-maven-plugin#380]
During the last cycle of generating the documentation site, apparently something went wrong and now the documentation for the goals is not available: https://cyclonedx.github.io/cyclonedx-maven-plugin/plugin-info.html

Start from here to see the rest of the site: https://cyclonedx.github.io/cyclonedx-maven-plugin/index.html

**Comment by hboutemy** [comment]
issue fixed by #381 , thanks for reporting

**Comment by malice00** [comment]
Thanks for the fast fix!
