### ISSUE TITLE
Parent BOM contains not deployed/installed modules

### ISSUE THREAD

**Issue by vy** [CycloneDX/cyclonedx-maven-plugin#409]
When using `makeAggregateBom` goal, if a submodule contains either `maven.install.skip`, `maven.deploy.skip`, or `cyclonedx.skip`, it shouldn't be included as a `component` in the parent module's `bom.xml`, whereas it is right now. This affects versions `<= 2.7.9`.

**Comment by vy** [comment]
@hboutemy, I would classify this ticket as a `bug`, since a module that is not used, not deployed, is being exposed as a component/dependency.

**Comment by hboutemy** [comment]
bug or enhancement, good question: this has never been a feature of the plugin, then not really a bug, the plugin works as expected until now

**Comment by hboutemy** [comment]
need to take same approach as https://issues.apache.org/jira/browse/MARTIFACT-34

**Comment by ppkarwasz** [comment]
Thanks @hboutemy,

I am working on a PR, can you assign me to the issue?
