### ISSUE TITLE
Reproducible `serialNumber` generation

### ISSUE THREAD

**Issue by ppkarwasz** [CycloneDX/cyclonedx-maven-plugin#420]
In order to allow the usage of BOM-links from external CycloneDX documents, the generated SBOM should always include a `serialNumber`.

Currently this is only generated if the reproducibility flag is disabled. We could improve the generation algorithm to generate a **deterministic** `serialNumber`. The generating algorithm might depend on:

- cryptographic hashes of a Maven module artifacts (SBOM excluded, obviously). We can restrict this to the hash of the POM file and **main** artifact,
- for the _aggregate_ BOM, it should also consider the serial numbers/hashes of its child modules.

**Comment by hboutemy** [comment]
done in #425
