### ISSUE TITLE
Possiblity to create SBOM even for not deployed artifacts

### ISSUE THREAD

**Issue by mszalbach** [CycloneDX/cyclonedx-maven-plugin#430]
With https://github.com/CycloneDX/cyclonedx-maven-plugin/pull/416 a feature was implemented which detects if the artifact of a Maven Module is deployed and the cyclonedx-maven-plugin will skip its execution, even when configured explicitly in this module.

There should be a config to disable this feature to be able to create SBOMs even when the deploy plugin is disabled. The state of deploying something to a Maven Central like repo or a Nexus/Artifactory instance has nothing to do with creating and providing SBOM, at least in a company context.

A Maven Module could produce some other artifact like a Docker image or an Zip which will be deployed somewhere else for production usage and I still want to create an SBOM for this.

**Comment by bstrdsmkr** [comment]
This broke for us. We build jars in a CI job, then copy them into a Docker container in a separate job so now SBOM generation is broken, which puts us out of compliance

**Comment by hboutemy** [comment]
is it about creating a separate SBOM for the Maven module?
or about adding the module in the aggregated SBOM?

**Comment by mszalbach** [comment]
My case was for creating the SBOM at all for the module. I currently have no use case for the makeAggregateBom and have no idea how the output will look like and what I would expect.

But from my point of view there is no realtionship between the deploy plugin and the cyclondx plugin and it would suprise me if something is missing just because some other developer decided we did not need a Jar for other Teams (by disabling deploy to Nexus/Artifactory).

I would exclude something by removing it from the POM, suescope filtering or ignore the module via exclude property.
