### ISSUE TITLE
Skip SPDX licence check

### ISSUE THREAD

**Issue by siewer** [CycloneDX/cyclonedx-maven-plugin#50]
I am running bom generation in command line with

mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

is it possible to somehow disable SPDX licence verification? CI slaves I am using have no possibility to connect to internet

**Comment by stevespringett** [comment]
Duplicate of #42 
Workaround:
```
mvn -DSPDXParser.OnlyUseLocalLicenses=true org.cyclonedx:cyclonedx-maven-plugin:1.6.4:makeAggregateBom
```
or
```
mvn -DSPDXParser.OnlyUseLocalLicenses=true org.cyclonedx:cyclonedx-maven-plugin:1.6.4:makeBom
```
