### ISSUE TITLE
Upgrade plans for Java 17 and maven 4

### ISSUE THREAD

**Issue by prabhu** [CycloneDX/cyclonedx-maven-plugin#504]
Maven 4 beta 3 is now available and requires Java 17 as minimum.

https://maven.apache.org/docs/4.0.0-beta-3/release-notes.html

Any plans to upgrade this plugin to the [v4](https://mvnrepository.com/artifact/org.apache.maven/maven-core/4.0.0-beta-3) [api](https://mvnrepository.com/artifact/org.apache.maven/maven-plugin-api/4.0.0-beta-3)?

**Comment by hboutemy** [comment]
upgrading to the v4 API would mean not supporting Maven 3 any more: is there any benefit expected?

**Comment by prabhu** [comment]
For multi-module projects, we can build SBOM with components only from specific projects (and their child projects).

https://maven.apache.org/guides/mini/guide-multiple-modules-4.html

Things like resume might also help.

Perhaps, it could be a separate plugin on a new repo?

**Comment by hboutemy** [comment]
Maven 4 supports Maven 3 plugins: it seems what you are looking for

**Comment by hboutemy** [comment]
closing issue, as plugin is currently compatible with Maven 4 and Java 17: nothing to do
