### ISSUE TITLE
Use maven plugin with ivy generated pom

### ISSUE THREAD

**Issue by bahrb** [CycloneDX/cyclonedx-maven-plugin#51]
Hello, 

we are using apache ivy for dependency management, backed by a private maven repository on an internal nexus server. So my thoughts are, to use ivy's [makepom](https://ant.apache.org/ivy/history/2.3.0/use/makepom.html) task to produce a pom and hand that over to the maven plugin to get a bom file from that.
But I don't know if it is possible to run maven with this plugin within a project which does not use maven at all. Is there a way to achieve this?

Thanks in advance!

**Comment by stevespringett** [comment]
That approach will likely work. The generated pom will need to include all the direct dependencies (at a minimum). Once the pom is created, you may need to ensure the dependencies are in the local .m2 directory. I don't know if the CycloneDX Maven plugin will automatically resolve or not. If not, then you'd likely need to execute `dependency:resolve` from the Maven Dependencies plugin prior to running the CycloneDX plugin. But the overall approach is seems fine.
