### ISSUE TITLE
Default component type is set to "library" for non-library submodules in multimodule Maven project

### ISSUE THREAD

**Issue by lonewalker0** [CycloneDX/cyclonedx-maven-plugin#521]
### Description

In a multimodule Maven project, some submodules are configured with the projectType: application setting in the CycloneDX Maven plugin. However, when generating the aggregated SBOM (Software Bill of Materials), these submodules still have the component type set to "library" by default. This behavior results in an incorrect component type assignment for those submodules.

### Steps to reproduce:

Create a multimodule Maven project.
Configure the CycloneDX Maven plugin in the parent POM.
In one of the submodules, set the projectType configuration to application.
Generate the aggregated SBOM using the CycloneDX Maven plugin.

### Expected behavior:
The aggregated SBOM should reflect the correct component type for each submodule based on their individual projectType configurations. Submodules configured as application should have their component type set to application.

### Actual behavior:
Submodules configured with projectType: application still have their component type set to library in the aggregated SBOM.

I also have a solution to address this issue.

**Comment by visomar** [comment]
I would like to ask if this expected behaviour would also differentiate the submodules and the external dependencies in case no projectType is defined in every module, as the SBOM aggregation process should have a way of categorizing both (it may not be using type though) and reflecting this distinction in every component/dependency in the final SBOM.

If the intention of this parameter is purely providing a configuration set by users of each module, then I think we could benefit from some parameter that also identifies every component in the way I described.

**Comment by lonewalker0** [comment]
If the project type in the submodules has not been set, then the default behavior is to consider them as 'library'. Regarding the addition of another parameter, I didn't understand what you mean.

**Comment by visomar** [comment]
To put it differently, I was asking if this change would allow the user obtaining the SBOM to identify if any of the `components` are indeed submodules of the project, or just external dependencies.

After seeing the change proposed in the PR, I suppose the answer is no in the general case, as the `project type` parameter's purpose is not meant for this identification (although in a particular case, one could use it for that).

The last part of my previous message stated that users (in which I'm included) could benefit from a parameter that would identify a component this way, allowing certain tools to modify these submodules with upgrades (not possible if they are just external dependencies).

**Comment by davidecavestro** [comment]
Given the following maven multi-project structure
```
.
├── app
│   └── pom.xml
├── lib-1
│   └── pom.xml
├── lib-2
│   └── pom.xml
└── pom.xml
```
this issue proposes a way to produce a SBOM where the _app_ component is marked with _[type](https://cyclonedx.org/docs/1.4/json/#components_items_type)_ `application`.
This is done simply adding the following to _app/pom.xml_
```pom.xml
<project...>
    <build>
        <plugins>
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>${current.version}</version>
                <configuration>
                    <projectType>application</projectType>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
while _lib-1_ and _lib-2_ components _type_ in the SBOM is still `library`.

@visomar could you please give an example of what you are proposing instead?
