### ISSUE TITLE
Selecting outputFormat=json does not honor outputDirectory

### ISSUE THREAD

**Issue by wepackard** [CycloneDX/cyclonedx-maven-plugin#526]
Maven Plugin v2.7.11
```
    <outputFormat>json</outputFormat>
    <outputDirectory>${project.directory}</outputDirectory>          

    <goal>makeAggregateBom</goal>
```

bom files are created in target folder

selecting an `outputFormat=all` places both generated BOM files in designated `outputDirectory`

**Comment by hboutemy** [comment]
`${project.directory}` refers to a non-existing property, then setting the value does nothing, whatever the value of `outputFormat`
Use `.` and you'll see that, this time, it works and does not write to `target` any more but the current directory

marking this issue as invalid: please reopen with a concrete reproducer and extract of output log if you really think there is an issue (which I doubt given how the code is written https://github.com/CycloneDX/cyclonedx-maven-plugin/blob/master/src/main/java/org/cyclonedx/maven/BaseCycloneDxMojo.java#L438 )
