### ISSUE TITLE
version 2.0.2 throwing issues with connection

### ISSUE THREAD

**Issue by thinksabin** [CycloneDX/cyclonedx-maven-plugin#59]
hi,
I'm suddenly facing the issue with connection reset error which wasnt faced in the previous build where version 1.6.4 was being used.

`

[ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.0.2:makeAggregateBom (default-cli) on project iker: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:2.0.2:makeAggregateBom failed: java.net.SocketException: Connection reset -> [Help 1]
--
21-Jul-2020 10:52:00 | org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.0.2:makeAggregateBom (default-cli) on project iker: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:2.0.2:makeAggregateBom failed: java.net.SocketException: Connection reset
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
21-Jul-2020 10:52:00 | at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
21-Jul-2020 10:52:00 | at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
21-Jul-2020 10:52:00 | at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
21-Jul-2020 10:52:00 | at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
21-Jul-2020 10:52:00 | at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
21-Jul-2020 10:52:00 | at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
21-Jul-2020 10:52:00 | at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
21-Jul-2020 10:52:00 | at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
21-Jul-2020 10:52:00 | at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
21-Jul-2020 10:52:00 | at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
21-Jul-2020 10:52:00 | at java.lang.reflect.Method.invoke (Method.java:498)
21-Jul-2020 10:52:00 | at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
21-Jul-2020 10:52:00 | at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
21-Jul-2020 10:52:00 | at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
21-Jul-2020 10:52:00 | at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
21-Jul-2020 10:52:00 | Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:2.0.2:makeAggregateBom failed: java.net.SocketException: Connection reset

`
Please help. Thanks.

**Comment by stevespringett** [comment]
It doesn't make outbound connections unless Maven is doing something behind the scenes. Do you have a pom that can reproduce this issue?

I personally test with dropwizard and keycloak projects since they're quite large multi-module Maven projects. But I have not run into this issue during testing.

**Comment by thinksabin** [comment]
hi Steve,
I have attached the pom.xml. Please suggest. Thanks.

[pom.xml.txt](https://github.com/CycloneDX/cyclonedx-maven-plugin/files/4955645/pom.xml.txt)

**Comment by stevespringett** [comment]
Looks like it doesn't work without the parent pom. Do you have a public project that also has this issue or is it possible to create a simple gist that can reproduce?

**Comment by thinksabin** [comment]
I'm afraid i wont be able to :(
I will try on some public project and will let you know.
