### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha3_256Hex(Ljava/io/InputStream;)Ljava/lang/String

### ISSUE THREAD

**Issue by wheredevel** [CycloneDX/cyclonedx-maven-plugin#76]
I tried several plugin version, starting from 2.0.3.
All fail with the same error message.

1.6.4 works OK.

Error
---
```
Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:2.0.3:makeAggregateBom failed: An API incompatibility was encountered while executing org.cyclonedx:cyclonedx-maven-plugin:2.0.3:makeAggregateBom: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha3_256Hex(Ljava/io/InputStream;)Ljava/lang/String;
```

**Comment by stevespringett** [comment]
The Maven plugin has the following dependency tree:
```
org.cyclonedx:cyclonedx-maven-plugin:2.1.1
    org.cyclonedx:cyclonedx-core-java:3.0.7
        commons-codec:commons-codec:1.15
```

commons-codec v1.12 and higher have the necessary sha3 methods. It appears the build in question is resolving an old version of commons-codec without these methods. Maven uses a 'nearest neighbor' approach to dependency resolution. Most of the time this approach works fine, but in this case, it seems like you may have to tweak the pom to ensure commons-codec 1.12 and higher is resolved.

Older versions of this Maven plugin did not generate SHA3, so therefore it was not an issue - although older versions of the plugin has other issues.

I'd recommend tweaking the pom to correct the resolution issue.

**Comment by Marx314** [comment]
It depends on the plugin defined(pulled?) before cyclonedx.

I've seen a project go from the buildscripts dependencies (gradle in our case):
```
io.swagger.codegen.v3:swagger-codegen:3.0.18
```
to:
```
gradle.plugin.org.hidetake:gradle-swagger-generator-plugin:2.16.0
io.swagger:swagger-codegen-cli:2.3.1
```
This change made the exact same exception so I assume either swagger-codegen-cli or the gradle-swagger-generator-plugin pull an old version of commons-codec...

**Comment by au-alex** [comment]
Was this issue resolved? I am facing the same when trying to add cyclonedx plugin to an existing project. The project itself uses Apache httpclient that I think is packaged with commons-codec:1.11. The following didn't work for me:

**Comment by hboutemy** [comment]
ITs were added that show that recent versions work
if you have a case that does not work, please open a new issue with reproducer
