### ISSUE TITLE
cyclonedx-maven-plugin is not marked with @threadSafe run in Multi threaded maven build

### ISSUE THREAD

**Issue by rvsoni** [CycloneDX/cyclonedx-maven-plugin#77]
From maven build log,

mvn -T 4 clean install

[WARNING] The following plugins are not marked @threadSafe in A-Project: [WARNING] org.cyclonedx:cyclonedx-maven-plugin:2.1.0`
`

**Comment by Aljodomo** [comment]
+1

**Comment by stevespringett** [comment]
I think some investigation needs to be done to determine if the plugin is thread safe or not. I think it is, but if anyone wants to verify that, that would be great.

**Comment by penzhang** [comment]
+1

**Comment by hboutemy** [comment]
I'll have a second look at the code to check if I see anything that would prevent the goal to be thread safe...

**Comment by stevespringett** [comment]
Implemented in #264. Having to manual close as a bug in GitHub itself prevented the PR from closing and this ticket to be updated as well. Thanks again @hboutemy for confirming the code was thread safe and for putting in the proper Maven flags to indicate such.

**Comment by ndimiduk** [comment]
FYI @stevespringett : https://issues.apache.org/jira/browse/HBASE-27634 . We're on the latest 2.7.3.

**Comment by stevespringett** [comment]
@ndimiduk FYI 2.7.4 is the latest.

**Comment by beettlle** [comment]
@stevespringett I don't think this is working properly even on 2.7.4. To @ndimiduk 's point, this is from my HBase build.

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Apache HBase Shaded Packaging Invariants (with Hadoop bundled):
[WARNING] org.cyclonedx:cyclonedx-maven-plugin:2.7.4
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
```
