### ISSUE TITLE
Support for configuration of BOM filename

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-maven-plugin#81]
It would be useful if configuration options included the ability to specify the filename of the output BOM.  Currently the name is just `bom.xml` (and/or `bom.json`) and this can result in a pipeline job that performs BOM generation more than once resulting in the 2nd BOM over-writing the 1st.

Suggest  (where `bom` is default):

        <configuration>
            <outputFilename>bom</outputFilename>
        </configuration>

In my pipelline case, tweaking  `bom` to something like `${project.artifactId}` would be sufficient to prevent over-write.

Ideally, the filename should also be included in log output (See also #80)

**Comment by stevespringett** [comment]
Defaults to `bom` if not specified.

Usage:
```xml
<outputName>inventory</outputName>
```
