### ISSUE TITLE
How to mimic effective pom to determine the exact version

### ISSUE THREAD

**Issue by prabhu** [CycloneDX/cyclonedx-maven-plugin#90]
When we produce bom for https://github.com/prabhu/copper-cms we get jackson-databind@2.6.6 via the module `chemistry-opencmis-test-tck`.

```
{
      "ref": "pkg:maven/com.amazonaws/aws-java-sdk-core@1.11.98?type=jar",
      "dependsOn": [
        "pkg:maven/commons-logging/commons-logging@1.1.3?type=jar",
        "pkg:maven/org.apache.httpcomponents/httpclient@4.5.2?type=jar",
        "pkg:maven/software.amazon.ion/ion-java@1.0.2?type=jar",
        "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.6.6?type=jar",
        "pkg:maven/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor@2.6.6?type=jar",
        "pkg:maven/joda-time/joda-time@2.8.1?type=jar"
      ]
    }
```

There is a direct dependency on jackson-databind@2.12.0 in copper-server https://github.com/prabhu/copper-cms/blob/master/copper-server/pom.xml#L83

However, when we package the app copper-server, the war only contains version 2.12.0 since the module `chemistry-opencmis-test-tck` is not a dependency for copper-server. Performing `mvn help:effective-bom` is correctly representing this behaviour.

Any ideas how this behaviour can be mimicked with the generated bom.xml or json file? Attached is the file in txt format.

[bom.json.txt](https://github.com/CycloneDX/cyclonedx-maven-plugin/files/6118117/bom.json.txt)

**Comment by CMYanko** [comment]
databind 2.12.0 is in that file also

**Comment by CMYanko** [comment]
if we ran the cyclone dx plugin in the deliverable folder adn not the root we might get a more concise set of findings

**Comment by prabhu** [comment]
Thanks @CMYanko . Your tip worked!
